# Generated by Django 2.1.7 on 2019-04-18 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cols',
        ),
    ]
